---
default_language_version:
  python: "3.12"
repos:
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.377
    hooks:
    - id: pyright

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
        stages: ["commit"]
      - id: trailing-whitespace
        stages: ["commit"]
      - id: mixed-line-ending
        stages: ["commit"]

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.41.0
    hooks:
      - id: markdownlint-fix

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.6.1"
    hooks:
      - id: ruff
        args: ["--fix", "--exit-non-zero-on-fix"]
      - id: ruff-format
